# Generated by Django 3.0.7 on 2020-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(max_length=20),
        ),
    ]
